### ISSUE TITLE
Errors on scene shutdown

### ISSUE THREAD

**Issue by aprotopsaltis** [papagiannakis/Elements#23]
Some errors are generated on scene shutdown. It is probably related to VertexArray. 
All examples, except 1,2 and 11, have this issue. Also, when running the code with the debugger the error is filtered.

Unable to import OpenGL.arrays.lists.ListHandler: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function VertexArray.__del__ at 0x7fd074d10ca0>
Traceback (most recent call last):
  File "/Users/antonisprotopsaltis/Documents/docs/work/ORAMAVR/src/Elements/Elements/pyGLV/GL/VertexArray.py", line 88, in __del__
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 114, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 212, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 55, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
TypeError: ("No array-type handler for type <class 'list'> (value: [2]) registered", None)
Unable to import OpenGL.arrays.lists.ListHandler: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function VertexArray.__del__ at 0x7fd074d10ca0>
Traceback (most recent call last):
  File "/Users/antonisprotopsaltis/Documents/docs/work/ORAMAVR/src/Elements/Elements/pyGLV/GL/VertexArray.py", line 88, in __del__
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 114, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 212, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 55, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
TypeError: ("No array-type handler for type <class 'list'> (value: [3]) registered", None)
Unable to import OpenGL.arrays.lists.ListHandler: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <function VertexArray.__del__ at 0x7fd074d10ca0>
Traceback (most recent call last):
  File "/Users/antonisprotopsaltis/Documents/docs/work/ORAMAVR/src/Elements/Elements/pyGLV/GL/VertexArray.py", line 88, in __del__
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 299, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 161, in OpenGL_accelerate.wrapper.PyArgCalculator.c_call
  File "src/wrapper.pyx", line 128, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 114, in OpenGL_accelerate.wrapper.PyArgCalculatorElement.c_call
  File "src/wrapper.pyx", line 212, in OpenGL_accelerate.wrapper.CallFuncPyConverter.c_call
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 55, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
TypeError: ("No array-type handler for type <class 'list'> (value: [4]) registered", None)

**Comment by kamarianakis** [comment]
Using atexit seems to resolve all issues, at least on Mac. Resolved for Mac in #51
